services:
  postgresql-master:
    image: docker.io/bitnami/postgresql:17
    container_name: postgresql-master
    ports:
      - '5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
      #:/opt/bitnami/postgresql/conf
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=PkAX16o639vwj5u
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=PkAX16o639vwj5u
      - POSTGRESQL_DATABASE=issuer
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - postgres_network
      
  postgresql-slave:
    image: docker.io/bitnami/postgresql:17
    container_name: postgresql-slave
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=PkAX16o639vwj5u
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=PkAX16o639vwj5u
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes      
    networks:
      - postgres_network
   
      
  pgadmin:
    image: dpage/pgadmin4:8.12.0
    container_name: pgadmin
    restart: always
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - postgresql-master
      - postgresql-slave
    links:
      - postgresql-master
      - postgresql-slave      
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ~/volumes/data/pgbackup/_data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres_network

volumes:
  postgresql_master_data:
    driver: local
    
networks:
  postgres_network:
    driver: bridge

